<?php
// Voci menu
o2def::menu_item("", "M", "base", "", "", True, True, "");
o2def::menu_item("base", "M", "archivi", "Archivi", "", True, True, "menu/archivi.png");
o2def::menu_item("archivi", "P", "parametri", "Parametri", "parametri", True, True, "menu/parametri.png");
o2def::menu_item("archivi", "P", "anagrafica", "Anagrafica", "anagrafica", True, True, "menu/anagrafica.png");
o2def::menu_item("archivi", "P", "contratti", "Contratti", "contratti", True, True, "menu/contratti.png");
o2def::menu_item("base", "M", "documenti", "Documenti", "", True, True, "menu/documenti.png");
o2def::menu_item("documenti", "P", "fatture", "Fatture", "fatture", True, True, "menu/fatture.png");
o2def::menu_item("documenti", "P", "spese", "Spese", "spese", True, True, "menu/spese.png");
o2def::menu_item("documenti", "P", "presentazioni", "Presentazioni", "presentazioni", True, True, "menu/presentazioni.png");
o2def::menu_item("base", "P", "scadenze", "Scadenze", "scadenze", True, True, "menu/scadenze.png");
?>
